version: 2
jobs:
  build:
    environment:
      IMAGE_SUFFIX: 'shopify-test-template'
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/python:2.7.15 # the primary container, where your job's commands are run
    working_directory: ~/repo
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run: curl -s https://raw.githubusercontent.com/Shopify/themekit/master/scripts/install | sudo python
      - run: theme version
